language: java
jdk:
  - openjdk8

before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull openjdk:8-jre-alpine
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
install: true

script:
  - ./mvnw clean install -B
  - ./mvnw clean package -DskipTests=true
  - ./mvnw deploy jib:build -P deploy-docker
